# -*- coding: utf-8 -*-
"""tesseract_text_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-iEN9NRcpiQAxgCbbqcimLPrPQdLGY9
"""

!pip install opencv-python

!sudo apt-get install tesseract-ocr
!sudo apt-get install libtesseract-dev

!pip install pytesseract

import cv2
from google.colab import drive
import pytesseract
drive.mount('/content/gdrive')
img = cv2.imread('gdrive/My Drive/test-image.jpg')
print("Loaded")

text= pytesseract.image_to_string('gdrive/My Drive/test-image.jpg',lang='eng')
print("First test: ", text)
print("")
text1= pytesseract.image_to_string('gdrive/My Drive/test-image-2.png',lang='eng')
print("Second test: ", text1)